MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "../params/adap_retina_sm_tinyperson_b4/model_only_model_final.pth"
  RPN_ONLY: True
  RETINANET_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    NUM_CLASSES: 2
    ANCHOR_SIZES: (8, 16, 32, 64, 128)  # (4, 8, 16, 32, 64) will be better
    ASPECT_RATIOS: (0.5, 1., 2)
    ANCHOR_STRIDES: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N: 1000
    BBOX_REG_WEIGHT: 4.0
    LOSS_ALPHA: 0.25 # 0.25
    LOSS_GAMMA: 2.0
    PRIOR_PROB: 0.01
DATASETS:
  TRAIN: ("tiny_set_corner_sw640_sh512_erase_with_uncertain_train_all_coco",)
  TEST: ("tiny_set_corner_sw640_sh512_test_all_coco",)
#  TEST: ("voc_2007_test",)
INPUT:
  USE_SCALE: true
  SCALES: (1,)
DATALOADER:
  SIZE_DIVISIBILITY: 32

# 1 gpu
SOLVER:
  CHECKPOINT_PERIOD: 1603   # 2 epoch
  TEST_ITER: 1603   # 1 epoch
  BASE_LR: 0.005
#  HEAD_LR_FACTOR: 10.
  WEIGHT_DECAY: 0.0001
  STEPS: (9618, 16030)   # (6 epoch, 10 epoch)
  MAX_ITER: 19236 # 12 epoch
  IMS_PER_BATCH: 2
  NUM_GPU: 2
TEST:
  IMS_PER_BATCH: 2
  COCO_EVALUATE_STANDARD: 'tiny'  # tiny need change
  MERGE_RESULTS: true
  MERGE_GT_FILE: '/home/hui/dataset/tiny_set/annotations/task/tiny_set_test_all.json'
  IGNORE_UNCERTAIN: true
  USE_IOD_FOR_IGNORE: true
OUTPUT_DIR: ./outputs/tiny_set/retina/baseline2_lrfpn_smb4coco
